name: Godot Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download Godot Engine
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
      - name: Install Godot
        run: |
          unzip Godot_v4.3-stable_linux.x86_64.zip

      - name: Run Tests
        run: |
          ./Godot_v4.3-stable_linux.x86_64 --headless \
          -s addons/gdUnit4/bin/GdUnitCmdTool.gd -a run
